title:               Ryan O
url:                 https://rynonl.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Ryan O'Neill
  url:               rynonl.github.io
  email:             rco8786@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
